/**
 * 
 */
package de.dfki.resc28.realsense4j.util;

/**
 * @author resc01
 *
 */
public enum Stream 
{
	/**
	 * Native stream of depth data produced by RealSense device
	 */
	DEPTH (0),
	/**
	 * Native stream of color data captured by RealSense device
	 */
	COLOR (1),
	/**
	 * Native stream of infrared data captured by RealSense device
	 */
	INFRARED (2),
	/**
	 * Native stream of infrared data captured from a second viewpoint by RealSense device
	 */
	INFRARED2 (3),
	/**
	 * Synthetic stream containing point cloud data generated by deprojecting the depth image
	 */
	POINTS (4),
	/**
	 * Synthetic stream containing undistorted color data with no extrinsic rotation from the depth stream
	 */
	RECTIFIED_COLOR (5),
	/**
	 * Synthetic stream containing color data but sharing intrinsics of depth stream
	 */
	COLOR_ALIGNED_TO_DEPTH (6),
	/**
	 * Synthetic stream containing second viewpoint infrared data but sharing intrinsics of depth stream
	 */
	INFRARED2_ALIGNED_TO_DEPTH (7),
	/**
	 * Synthetic stream containing depth data but sharing intrinsics of color stream
	 */
	DEPTH_ALIGNED_TO_COLOR (8),
	/**
	 * Synthetic stream containing depth data but sharing intrinsics of rectified color stream
	 */
	DEPTH_ALIGNED_TO_RECTIFIED_COLOR (9),
	/**
	 * Synthetic stream containing depth data but sharing intrinsics of second viewpoint infrared stream
	 */
	DEPTH_ALIGNED_TO_INFRARED2 (10);
	
	Stream(int streamCode) 
	{
		m_streamCode = streamCode ;
	}
	
	private final int m_streamCode;
}
